"""Séquence 1 de l'application Compagnon FLE.

Questions 001 à 005 : banque de référence du 27 juillet 2026 à 18 h 47.
Questions 006 à 010 : sauvegarde validée avant intégration de la séquence 1.
Le contenu pédagogique est conservé tel qu'il apparaît dans les sources.
"""

LEVELS = ("A0", "A1", "A2", "B1", "B2")

SEQUENCE_1 = {
    "slug": "sequence-1",
    "title": "Séquence 1 — Me connaître et vous connaître",
    "levels": {'A0': [{'id': 'S1-A0-001',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Présent — s’appeler',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'Je ___ Samir.',
         'choices': {'A': 'm’appelle', 'B': 'appelle', 'C': 'suis'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'La présentation commence par « Je m’appelle… ».',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A0-002',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Présent — avoir',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'J’___ 17 ans.',
         'choices': {'A': 'ai', 'B': 'suis', 'C': 'habite'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Pour dire l’âge, on utilise « avoir ».',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A0-003',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Présent — venir',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'Je ___ du Soudan.',
         'choices': {'A': 'viens', 'B': 'habite', 'C': 'prépare'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Cherche le verbe utilisé pour dire l’origine.',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A0-004',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Présent — habiter',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'J’___ à Bordeaux.',
         'choices': {'A': 'habite', 'B': 'viens', 'C': 'ai'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Cherche le verbe utilisé pour dire la ville.',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A0-005',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Mot interrogatif — identité',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': '___ t’appelles-tu ?',
         'choices': {'A': 'Comment', 'B': 'Où', 'C': 'Pourquoi'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'La question cherche le prénom.',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A0-006',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Reconnaître une langue',
         'modality': 'Compréhension écrite',
         'source_type': 'QCM',
         'type': 'single_choice',
         'instruction': 'Quelle phrase parle d’une langue ?',
         'support': 'Trois phrases courtes.',
         'choices': {'A': 'Je parle soninké.',
                     'B': 'J’habite à Bordeaux.',
                     'C': 'J’ai 17 ans.',
                     'D': 'J’aime le vélo.'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Oui, « soninké » est une langue.',
         'feedback_error': 'Cherche « je parle ».',
         'help': 'Afficher une icône de bouche.',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A0-007',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Exprimer un goût simple',
         'modality': 'Compréhension écrite',
         'source_type': 'Choix image-phrase',
         'type': 'single_choice',
         'instruction': 'Choisis la phrase qui correspond à l’image.',
         'support': 'Image : ballon de football',
         'choices': {'A': 'J’aime le football.',
                     'B': 'Je viens de Guinée.',
                     'C': 'J’ai 18 ans.',
                     'D': 'Je parle français.'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo.',
         'feedback_error': 'Regarde l’objet sur l’image.',
         'help': 'Faire entendre « J’aime… ».',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A0-008',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Remettre une présentation en ordre',
         'modality': 'Compréhension écrite',
         'source_type': 'Classement',
         'type': 'single_choice',
         'instruction': 'Mets les éléments dans un ordre possible.',
         'support': 'Prénom / âge / pays',
         'choices': {'A': 'Âge → pays → prénom',
                     'B': 'Prénom → âge → pays',
                     'C': 'Pays → prénom → âge',
                     'D': 'Toutes les réponses sont impossibles'},
         'correct_answer': 'B',
         'source_expected_answer': 'B',
         'feedback_success': 'Oui, c’est un ordre clair.',
         'feedback_error': 'Commence par le prénom.',
         'help': 'Afficher 1. Je m’appelle…',
         'estimated_duration': '2 min',
         'difficulty': 2,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A0-009',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Repérer deux informations',
         'modality': 'Compréhension orale',
         'source_type': 'Sélection multiple',
         'type': 'multiple_choice',
         'instruction': 'Écoute et choisis deux informations vraies.',
         'support': 'Audio : « Je m’appelle Ali. J’ai 17 ans. »',
         'choices': {'A': 'Il s’appelle Ali.',
                     'B': 'Il a 17 ans.',
                     'C': 'Il habite à Paris.',
                     'D': 'Il aime le basket.'},
         'correct_answer': 'A+B',
         'source_expected_answer': 'A+B',
         'feedback_success': 'Bravo, tu as repéré deux informations.',
         'feedback_error': 'Réécoute phrase par phrase.',
         'help': 'Pause automatique entre les phrases.',
         'estimated_duration': '2 min',
         'difficulty': 2,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A0-010',
         'sequence': 1,
         'level': 'A0',
         'competency': 'Compléter une présentation très guidée',
         'modality': 'Production écrite courte',
         'source_type': 'Texte à trous',
         'type': 'single_choice',
         'instruction': 'Complète avec les mots proposés.',
         'support': '« Je m’_____ Sara. J’_____ 18 ans. »',
         'choices': {'A': 'appelle / ai',
                     'B': 'habite / aime',
                     'C': 'parle / suis',
                     'D': 'viens / fais'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Très bien.',
         'feedback_error': 'Écoute la phrase complète.',
         'help': 'Audio + mots glissables.',
         'estimated_duration': '2 min',
         'difficulty': 2,
         'source_group': 'complement_006_010',
         'manual_review': False}],
 'A1': [{'id': 'S1-A1-001',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Mot interrogatif — lieu',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': '___ habites-tu ?',
         'choices': {'A': 'Où', 'B': 'Quel', 'C': 'Combien'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'La question cherche un lieu.',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A1-002',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Mot interrogatif — âge',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': '___ âge as-tu ?',
         'choices': {'A': 'Quel', 'B': 'Pourquoi', 'C': 'Comment'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Le nom « âge » est masculin.',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A1-003',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Présent — préparer',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'Je ___ un CAP cuisine.',
         'choices': {'A': 'prépare', 'B': 'prépares', 'C': 'préparons'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Le sujet est « je ».',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A1-004',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Présent — aimer',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'J’___ écouter de la musique.',
         'choices': {'A': 'aime', 'B': 'aimes', 'C': 'aimons'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Le sujet est « je ».',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A1-005',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Préposition de lieu',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'J’habite ___ Bègles.',
         'choices': {'A': 'à', 'B': 'de', 'C': 'du'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Devant une ville, on utilise généralement « à ».',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A1-006',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Construire une présentation simple',
         'modality': 'Production écrite guidée',
         'source_type': 'Remise en ordre',
         'type': 'ordering',
         'instruction': 'Remets les phrases dans un ordre logique.',
         'support': '4 phrases mélangées.',
         'choices': {'A': 'Je m’appelle…', 'B': 'J’ai… ans.', 'C': 'J’habite…', 'D': 'J’aime…'},
         'correct_answer': 'A-B-C-D',
         'source_expected_answer': '1-2-3-4',
         'feedback_success': 'C’est clair et logique.',
         'feedback_error': 'Commence par l’identité.',
         'help': 'Numéroter la première phrase.',
         'estimated_duration': '2 min',
         'difficulty': 1,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A1-007',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Vérifier une information',
         'modality': 'Interaction écrite simulée',
         'source_type': 'QCM dialogue',
         'type': 'single_choice',
         'instruction': 'Quelle réponse vérifie l’information ?',
         'support': '« Tu habites bien à Lormont ? »',
         'choices': {'A': 'Oui, j’habite à Lormont.',
                     'B': 'J’ai 18 ans.',
                     'C': 'Je viens du Mali.',
                     'D': 'Il aime le sport.'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Exact.',
         'feedback_error': 'La question parle du lieu de vie.',
         'help': 'Surligner « Lormont ».',
         'estimated_duration': '1 min',
         'difficulty': 1,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A1-008',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Décrire simplement une personne',
         'modality': 'Compréhension écrite',
         'source_type': 'Choix multiple',
         'type': 'multiple_choice',
         'instruction': 'Choisis deux phrases qui décrivent la personne.',
         'support': 'Photo d’un jeune souriant avec lunettes',
         'choices': {'A': 'Il porte des lunettes.',
                     'B': 'Il sourit.',
                     'C': 'Il vient de Guinée.',
                     'D': 'Il a 20 ans.'},
         'correct_answer': 'A+B',
         'source_expected_answer': 'A+B',
         'feedback_success': 'Très bien.',
         'feedback_error': 'Décris seulement ce que tu vois.',
         'help': 'Zoom sur la photo.',
         'estimated_duration': '2 min',
         'difficulty': 2,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A1-009',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Présenter un camarade',
         'modality': 'Production orale guidée',
         'source_type': 'Enregistrement',
         'type': 'manual_response',
         'instruction': 'Présente ton camarade avec trois informations.',
         'support': 'Trame : prénom / pays ou ville / goût',
         'choices': {},
         'correct_answer': 'Réponse libre avec 3 informations',
         'source_expected_answer': 'Réponse libre avec 3 informations',
         'feedback_success': 'Bravo, ta présentation est complète.',
         'feedback_error': 'Utilise « il » ou « elle ».',
         'help': 'Afficher trois amorces de phrases.',
         'estimated_duration': '3 min',
         'difficulty': 2,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-A1-010',
         'sequence': 1,
         'level': 'A1',
         'competency': 'Comprendre une fiche personnelle',
         'modality': 'Compréhension écrite',
         'source_type': 'QCM document',
         'type': 'single_choice',
         'instruction': 'Quelle langue parle la personne ?',
         'support': 'Mini-fiche : Nom, âge, ville, langue',
         'choices': {'A': 'Arabe', 'B': 'Bordeaux', 'C': '19 ans', 'D': 'Diallo'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo.',
         'feedback_error': 'Regarde la ligne « langue ».',
         'help': 'Surligner la rubrique utile.',
         'estimated_duration': '2 min',
         'difficulty': 1,
         'source_group': 'complement_006_010',
         'manual_review': False}],
 'A2': [{'id': 'S1-A2-001',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Interrogation — raison',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': '___ as-tu choisi cette formation ?',
         'choices': {'A': 'Pourquoi', 'B': 'Où', 'C': 'Combien'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'La question cherche une raison.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A2-002',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Passé composé — choisir',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'J’___ choisi ce CAP parce que j’aime cuisiner.',
         'choices': {'A': 'ai', 'B': 'suis', 'C': 'vais'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Le verbe « choisir » se construit ici avec « avoir ».',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A2-003',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Expression de la cause',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'Je prépare un CAP peinture ___ j’aime dessiner.',
         'choices': {'A': 'parce que', 'B': 'mais', 'C': 'quand'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'La deuxième partie donne la raison.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A2-004',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Depuis + durée',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'J’habite en France ___ deux ans.',
         'choices': {'A': 'depuis', 'B': 'pendant', 'C': 'dans'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'L’action a commencé avant et continue maintenant.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A2-005',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Reformulation — connecteur',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': '___, tu habites à Cenon depuis trois mois.',
         'choices': {'A': 'Donc', 'B': 'Pourquoi', 'C': 'Combien'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Le professeur reprend l’information donnée.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-A2-006',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Distinguer fait et opinion simple',
         'modality': 'Compréhension écrite',
         'source_type': 'QCM',
         'type': 'single_choice',
         'instruction': 'Quelle phrase est une opinion ?',
         'support': 'Quatre phrases sur une personne',
         'choices': {'A': 'Elle a 19 ans.',
                     'B': 'Elle habite à Bordeaux.',
                     'C': 'Je trouve qu’elle est très courageuse.',
                     'D': 'Elle parle français.'},
         'correct_answer': 'C',
         'source_expected_answer': 'C',
         'feedback_success': 'Exact.',
         'feedback_error': 'Une opinion montre ce que pense l’auteur.',
         'help': 'Surligner « je trouve que ».',
         'estimated_duration': '2 min',
         'difficulty': 2,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A2-007',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Rédiger une présentation courte',
         'modality': 'Production écrite guidée',
         'source_type': 'Réponse courte',
         'type': 'manual_response',
         'instruction': 'Rédige 5 à 6 phrases pour présenter une personne.',
         'support': 'Fiche d’informations fournie',
         'choices': {},
         'correct_answer': 'Texte cohérent avec identité, lieu, langue, goût et une '
                           'caractéristique',
         'source_expected_answer': 'Texte cohérent avec identité, lieu, langue, goût et une '
                                   'caractéristique',
         'feedback_success': 'Présentation claire.',
         'feedback_error': 'Vérifie les pronoms et l’ordre des informations.',
         'help': 'Plan guidé activable.',
         'estimated_duration': '6 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-A2-008',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Comprendre un portrait',
         'modality': 'Compréhension écrite',
         'source_type': 'Sélection multiple',
         'type': 'multiple_choice',
         'instruction': 'Choisis les informations présentes dans le texte.',
         'support': 'Portrait de 90 mots',
         'choices': {'A': 'apparence', 'B': 'caractère', 'C': 'goûts', 'D': 'adresse complète'},
         'correct_answer': 'A+B+C',
         'source_expected_answer': 'A+B+C',
         'feedback_success': 'Bravo.',
         'feedback_error': 'Relis chaque paragraphe.',
         'help': 'Découpage du texte en trois parties.',
         'estimated_duration': '3 min',
         'difficulty': 2,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A2-009',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Relier les idées',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM',
         'type': 'single_choice',
         'instruction': 'Choisis le bon connecteur.',
         'support': '« Il est réservé, _____ il participe toujours au travail de groupe. »',
         'choices': {'A': 'mais', 'B': 'parce que', 'C': 'd’abord', 'D': 'donc'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Exact.',
         'feedback_error': 'Il y a une opposition.',
         'help': 'Afficher deux flèches opposées.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'complement_006_010',
         'manual_review': False},
        {'id': 'S1-A2-010',
         'sequence': 1,
         'level': 'A2',
         'competency': 'Présenter une personne oralement',
         'modality': 'Production orale',
         'source_type': 'Enregistrement préparé',
         'type': 'manual_response',
         'instruction': 'Présente une personne que tu connais en 45 secondes.',
         'support': 'Plan facultatif : identité / activités / caractère / raison du choix',
         'choices': {},
         'correct_answer': 'Production libre organisée',
         'source_expected_answer': 'Production libre organisée',
         'feedback_success': 'Bravo, tu as organisé ta présentation.',
         'feedback_error': 'Utilise le plan si nécessaire.',
         'help': 'Notes brèves autorisées.',
         'estimated_duration': '5 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True}],
 'B1': [{'id': 'S1-B1-001',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Interrogation développée',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'Quelle question demande une motivation ?',
         'choices': {'A': 'Pourquoi as-tu choisi cette formation ?',
                     'B': 'Où habites-tu ?',
                     'C': 'Quel âge as-tu ?'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Une motivation explique un choix.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B1-002',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Conditionnel de politesse',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': '___-vous répéter, s’il vous plaît ?',
         'choices': {'A': 'Pourriez', 'B': 'Pouvez', 'C': 'Deviez'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Le conditionnel rend la demande plus polie.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B1-003',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Reformulation avec si',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': '___ je comprends bien, tu veux travailler en équipe.',
         'choices': {'A': 'Si', 'B': 'Parce que', 'C': 'Depuis'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Cette expression sert à vérifier qu’on a bien compris.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B1-004',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Relance adaptée',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': '— J’ai choisi la cuisine parce que j’aime créer.\n— ___',
         'choices': {'A': 'Peux-tu donner un exemple ?',
                     'B': 'Quel âge as-tu ?',
                     'C': 'Où habites-tu ?'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'La relance doit approfondir la réponse précédente.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B1-005',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Coordination — opposition',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'J’aime travailler en équipe, ___ je préfère préparer les desserts seul.',
         'choices': {'A': 'mais', 'B': 'donc', 'C': 'parce que'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Les deux idées s’opposent.',
         'estimated_duration': '1 min',
         'difficulty': 2,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B1-006',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Distinguer fait, impression et jugement',
         'modality': 'Compréhension écrite',
         'source_type': 'Catégorisation',
         'type': 'manual_response',
         'instruction': 'Classe chaque phrase.',
         'support': '6 phrases',
         'choices': {'A': 'Fait',
                     'B': 'Impression',
                     'C': 'Jugement argumenté',
                     'D': 'Impossible à classer'},
         'correct_answer': 'Classement attendu',
         'source_expected_answer': 'Classement attendu',
         'feedback_success': 'Bravo.',
         'feedback_error': 'Cherche les marqueurs : date, « semble », « je pense ».',
         'help': 'Définitions disponibles.',
         'estimated_duration': '4 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-B1-007',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Utiliser cause et conséquence',
         'modality': 'Grammaire en contexte',
         'source_type': 'Texte à trous',
         'type': 'manual_response',
         'instruction': 'Complète avec parce que, donc, grâce à ou pourtant.',
         'support': '4 phrases liées au parcours',
         'choices': {'A': 'parce que', 'B': 'donc', 'C': 'grâce à', 'D': 'pourtant'},
         'correct_answer': 'Réponses selon contexte',
         'source_expected_answer': 'Réponses selon contexte',
         'feedback_success': 'Très bien.',
         'feedback_error': 'Observe la relation logique.',
         'help': 'Indice par symbole.',
         'estimated_duration': '3 min',
         'difficulty': 2,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-B1-008',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Présenter une personne admirée',
         'modality': 'Production orale',
         'source_type': 'Enregistrement',
         'type': 'manual_response',
         'instruction': 'Présente une personne que tu admires et justifie ton choix.',
         'support': 'Consigne + minuteur 1 min 30',
         'choices': {},
         'correct_answer': 'Présentation suivie avec au moins deux justifications',
         'source_expected_answer': 'Présentation suivie avec au moins deux justifications',
         'feedback_success': 'Présentation structurée.',
         'feedback_error': 'Ajoute un exemple ou une raison.',
         'help': 'Plan facultatif.',
         'estimated_duration': '6 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-B1-009',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Répondre à une relance',
         'modality': 'Interaction orale simulée',
         'source_type': 'Réponse audio',
         'type': 'manual_response',
         'instruction': 'Réponds : « Peux-tu donner un exemple précis ? »',
         'support': 'Question audio',
         'choices': {},
         'correct_answer': 'Réponse libre avec exemple cohérent',
         'source_expected_answer': 'Réponse libre avec exemple cohérent',
         'feedback_success': 'Bonne réponse à la relance.',
         'feedback_error': 'Commence par « Par exemple… ».',
         'help': 'Amorce affichable.',
         'estimated_duration': '3 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-B1-010',
         'sequence': 1,
         'level': 'B1',
         'competency': 'Réviser un texte',
         'modality': 'Production écrite',
         'source_type': 'Correction ciblée',
         'type': 'manual_response',
         'instruction': 'Corrige les répétitions et les pronoms.',
         'support': 'Texte de 90 mots avec 6 problèmes',
         'choices': {},
         'correct_answer': 'Texte corrigé',
         'source_expected_answer': 'Texte corrigé',
         'feedback_success': 'Révision réussie.',
         'feedback_error': 'Vérifie les répétitions de « il » et les accords.',
         'help': 'Surligner les zones à revoir.',
         'estimated_duration': '6 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True}],
 'B2': [{'id': 'S1-B2-001',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Subjonctif — nécessité',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'Il faut que tu ___ précisément ton parcours.',
         'choices': {'A': 'présentes', 'B': 'présenteras', 'C': 'présentais'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Après « il faut que », on utilise le subjonctif.',
         'estimated_duration': '1 min',
         'difficulty': 3,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B2-002',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Conditionnel — conseil',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'Pour rendre ta réponse plus précise, tu ___ donner un exemple.',
         'choices': {'A': 'pourrais', 'B': 'peux', 'C': 'pourras'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Le conditionnel permet de formuler un conseil atténué.',
         'estimated_duration': '1 min',
         'difficulty': 3,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B2-003',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Interrogation indirecte',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'Le professeur demande à l’élève ___ il a choisi cette formation.',
         'choices': {'A': 'pourquoi', 'B': 'est-ce que pourquoi', 'C': 'pourquoi est-ce que'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Dans l’interrogation indirecte, on ne conserve pas « est-ce que ».',
         'estimated_duration': '1 min',
         'difficulty': 3,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B2-004',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Concession + subjonctif',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': '___ il parle encore peu français, il explique clairement sa motivation.',
         'choices': {'A': 'Bien qu’', 'B': 'Parce qu’', 'C': 'Depuis qu’'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'La phrase exprime une opposition inattendue.',
         'estimated_duration': '1 min',
         'difficulty': 3,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B2-005',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Discours rapporté',
         'modality': 'Grammaire en contexte',
         'source_type': 'QCM — un clic',
         'type': 'single_choice',
         'instruction': 'Je sélectionne la bonne réponse.',
         'support': 'Youssef dit : « Je veux obtenir mon diplôme. »\n'
                    'La reformulation correcte est :',
         'choices': {'A': 'Youssef dit qu’il veut obtenir son diplôme.',
                     'B': 'Youssef dit qu’il voulait obtenir mon diplôme.',
                     'C': 'Youssef dit que je veux obtenir son diplôme.'},
         'correct_answer': 'A',
         'source_expected_answer': 'A',
         'feedback_success': 'Bravo, c’est la bonne réponse.',
         'feedback_error': 'Ce n’est pas encore la bonne forme.',
         'help': 'Il faut adapter le pronom sans changer le temps inutilement.',
         'estimated_duration': '1 min',
         'difficulty': 3,
         'source_group': 'reference_001_005',
         'manual_review': False},
        {'id': 'S1-B2-006',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Synthétiser plusieurs sources',
         'modality': 'Production écrite',
         'source_type': 'Synthèse courte',
         'type': 'manual_response',
         'instruction': 'Rédige un portrait de 120 mots à partir de trois documents.',
         'support': 'Photo, témoignage, notice biographique',
         'choices': {},
         'correct_answer': 'Texte synthétique, hiérarchisé et sans contradiction',
         'source_expected_answer': 'Texte synthétique, hiérarchisé et sans contradiction',
         'feedback_success': 'Synthèse réussie.',
         'feedback_error': 'Ne juxtapose pas les sources.',
         'help': 'Grille de planification.',
         'estimated_duration': '8 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-B2-007',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Nuancer un jugement',
         'modality': 'Lexique / production',
         'source_type': 'Réécriture',
         'type': 'manual_response',
         'instruction': 'Nuance cette affirmation trop catégorique.',
         'support': '« C’est une personne parfaite. »',
         'choices': {},
         'correct_answer': 'Formulation nuancée et justifiée',
         'source_expected_answer': 'Formulation nuancée et justifiée',
         'feedback_success': 'Bonne nuance.',
         'feedback_error': 'Utilise « semble », « dans certaines situations », « même si ».',
         'help': 'Banque d’expressions.',
         'estimated_duration': '3 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-B2-008',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Présenter sans plan fourni',
         'modality': 'Production orale',
         'source_type': 'Enregistrement long',
         'type': 'manual_response',
         'instruction': 'Dresse le portrait d’une personne qui t’a influencé.',
         'support': 'Minuteur 2 min',
         'choices': {},
         'correct_answer': 'Discours autonome, organisé, illustré et nuancé',
         'source_expected_answer': 'Discours autonome, organisé, illustré et nuancé',
         'feedback_success': 'Présentation solide.',
         'feedback_error': 'Vérifie la progression et les exemples.',
         'help': 'Auto-planification de 30 secondes.',
         'estimated_duration': '8 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-B2-009',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Réagir à une objection',
         'modality': 'Interaction orale simulée',
         'source_type': 'Réponse audio',
         'type': 'manual_response',
         'instruction': 'Réponds à l’objection : « Tu ne présentes que ses qualités. »',
         'support': 'Audio interlocuteur',
         'choices': {},
         'correct_answer': 'Réponse nuancée avec limite ou contre-exemple',
         'source_expected_answer': 'Réponse nuancée avec limite ou contre-exemple',
         'feedback_success': 'Bonne prise en compte de l’objection.',
         'feedback_error': 'Reconnais d’abord une limite.',
         'help': 'Amorce : « C’est vrai que…, cependant… ».',
         'estimated_duration': '4 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True},
        {'id': 'S1-B2-010',
         'sequence': 1,
         'level': 'B2',
         'competency': 'Améliorer la cohérence d’un texte',
         'modality': 'Production écrite',
         'source_type': 'Révision avancée',
         'type': 'manual_response',
         'instruction': 'Réorganise et améliore ce portrait.',
         'support': 'Texte de 180 mots avec ruptures et répétitions',
         'choices': {},
         'correct_answer': 'Version cohérente et enrichie',
         'source_expected_answer': 'Version cohérente et enrichie',
         'feedback_success': 'Révision pertinente.',
         'feedback_error': 'Travaille transitions, hiérarchie et reprises nominales.',
         'help': 'Afficher les critères un par un.',
         'estimated_duration': '9 min',
         'difficulty': 3,
         'source_group': 'complement_006_010',
         'manual_review': True}]},
}


def all_questions():
    return [
        question
        for level in LEVELS
        for question in SEQUENCE_1["levels"][level]
    ]


def question_by_id(question_id: str):
    return next(
        (question for question in all_questions() if question["id"] == question_id),
        None,
    )


def validate_sequence_1() -> None:
    questions = all_questions()
    identifiers = [question["id"] for question in questions]
    if len(questions) != 50 or len(set(identifiers)) != 50:
        raise ValueError("La séquence 1 doit contenir 50 questions uniques")
    for level in LEVELS:
        level_questions = SEQUENCE_1["levels"][level]
        expected_ids = [f"S1-{level}-{number:03d}" for number in range(1, 11)]
        if [question["id"] for question in level_questions] != expected_ids:
            raise ValueError(f"Série incomplète ou désordonnée pour {level}")
        if any(
            question["source_group"] != "reference_001_005"
            for question in level_questions[:5]
        ):
            raise ValueError(f"Source incorrecte pour les questions 001 à 005 de {level}")
        if any(
            question["source_group"] != "complement_006_010"
            or int(question["id"].rsplit("-", 1)[1]) < 6
            for question in level_questions[5:]
        ):
            raise ValueError(f"Import complémentaire interdit pour {level}")


validate_sequence_1()
